// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZRGmsw5ws_WyBdW01lrSu-sVhbFJTkI',
    appId: '1:1021019372872:web:79f62e50aefeff90e8c77d',
    messagingSenderId: '1021019372872',
    projectId: 'sample-firebase-ai-app-b279f',
    authDomain: 'sample-firebase-ai-app-b279f.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-b279f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVzXzlN6mORVrY0rO2GzqNxQq87d9f18',
    appId: '1:1021019372872:android:4a181673de18f674e8c77d',
    messagingSenderId: '1021019372872',
    projectId: 'sample-firebase-ai-app-b279f',
    storageBucket: 'sample-firebase-ai-app-b279f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5kmPfpc11nIUwz_77Oa4Y2yCNbczKOxM',
    appId: '1:1021019372872:ios:25cb361459df07f5e8c77d',
    messagingSenderId: '1021019372872',
    projectId: 'sample-firebase-ai-app-b279f',
    storageBucket: 'sample-firebase-ai-app-b279f.appspot.com',
    iosClientId: '1021019372872-3enbpq5nlf837c6rnk5sglojlq9s3pg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5kmPfpc11nIUwz_77Oa4Y2yCNbczKOxM',
    appId: '1:1021019372872:ios:25cb361459df07f5e8c77d',
    messagingSenderId: '1021019372872',
    projectId: 'sample-firebase-ai-app-b279f',
    storageBucket: 'sample-firebase-ai-app-b279f.appspot.com',
    iosClientId: '1021019372872-3enbpq5nlf837c6rnk5sglojlq9s3pg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZRGmsw5ws_WyBdW01lrSu-sVhbFJTkI',
    appId: '1:1021019372872:web:434d8beaa9e3a9b1e8c77d',
    messagingSenderId: '1021019372872',
    projectId: 'sample-firebase-ai-app-b279f',
    authDomain: 'sample-firebase-ai-app-b279f.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-b279f.appspot.com',
  );

}